const PDFDocument = require('pdfkit');
const { formatDate, letterGrade } = require('./helpers');

function generateReportCard({ student, school, grades, attendance, term, academicYear, res }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="report-card-${student.first_name}-${student.last_name}-${term}.pdf"`
  );
  doc.pipe(res);

  // Header
  doc.fontSize(22).fillColor('#4F46E5').text('SchoolHub', { align: 'center' });
  doc.fontSize(16).fillColor('#111827').text(school.name, { align: 'center' });
  doc.fontSize(12).fillColor('#6B7280').text(`Student Report Card — ${term} ${academicYear}`, { align: 'center' });
  doc.moveDown();

  // Divider
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').lineWidth(1).stroke();
  doc.moveDown();

  // Student Info
  doc.fontSize(11).fillColor('#111827');
  doc.text(`Student: ${student.first_name} ${student.last_name}`, { continued: true });
  doc.text(`   |   Generated: ${formatDate(new Date())}`, { align: 'right' });
  doc.moveDown(0.5);

  // Grades Table Header
  const tableTop = doc.y;
  const col = { subject: 50, assessment: 200, score: 320, max: 390, pct: 440, grade: 500 };

  doc.fontSize(10).fillColor('#FFFFFF');
  doc.rect(50, tableTop, 495, 22).fill('#4F46E5');
  doc.fillColor('#FFFFFF');
  doc.text('Subject', col.subject, tableTop + 6, { width: 140 });
  doc.text('Assessment', col.assessment, tableTop + 6, { width: 110 });
  doc.text('Score', col.score, tableTop + 6, { width: 60 });
  doc.text('Max', col.max, tableTop + 6, { width: 45 });
  doc.text('%', col.pct, tableTop + 6, { width: 50 });
  doc.text('Grade', col.grade, tableTop + 6, { width: 45 });

  let y = tableTop + 22;
  let totalPct = 0;
  let gradeCount = 0;

  grades.forEach((g, i) => {
    const pct = g.max_score > 0 ? Math.round((g.score / g.max_score) * 100) : 0;
    totalPct += pct;
    gradeCount++;

    const rowColor = i % 2 === 0 ? '#F9FAFB' : '#FFFFFF';
    doc.rect(50, y, 495, 20).fill(rowColor);
    doc.fillColor('#111827').fontSize(9);
    doc.text(g.subjects?.name || '-', col.subject, y + 5, { width: 140 });
    doc.text(g.assessment_type || '-', col.assessment, y + 5, { width: 110 });
    doc.text(String(g.score), col.score, y + 5, { width: 60 });
    doc.text(String(g.max_score), col.max, y + 5, { width: 45 });
    doc.text(`${pct}%`, col.pct, y + 5, { width: 50 });
    doc.text(letterGrade(pct), col.grade, y + 5, { width: 45 });
    y += 20;
  });

  // Overall Average
  y += 10;
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#E5E7EB').stroke();
  y += 10;
  const avg = gradeCount > 0 ? Math.round(totalPct / gradeCount) : 0;
  doc.fontSize(12).fillColor('#111827');
  doc.text(`Overall Average: ${avg}% — ${letterGrade(avg)}`, 50, y, { align: 'right' });

  // Attendance Summary
  if (attendance) {
    y += 40;
    doc.fontSize(12).fillColor('#4F46E5').text('Attendance Summary', 50, y);
    y += 20;
    doc.fontSize(10).fillColor('#111827');
    doc.text(`Present: ${attendance.present}`, 50, y);
    doc.text(`Absent: ${attendance.absent}`, 150, y);
    doc.text(`Late: ${attendance.late}`, 230, y);
    doc.text(
      `Attendance Rate: ${attendance.total > 0 ? Math.round((attendance.present / attendance.total) * 100) : 0}%`,
      310,
      y
    );
  }

  // Footer
  const pageBottom = doc.page.height - 50;
  doc.fontSize(8).fillColor('#9CA3AF').text('Generated by SchoolHub — Confidential', 50, pageBottom, { align: 'center' });

  doc.end();
}

module.exports = { generateReportCard };
